=== IanGarciaUnam/Criptography/Tarea1/ganzua-1.01-src/ganzua-1.01/schemata/AlphabetRules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://ganzua.sourceforge.net/rules"
            xmlns="http://ganzua.sourceforge.net/rules"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:lang="http://ganzua.sourceforge.net/languages"
            xmlns:cntry="http://ganzua.sourceforge.net/countries"
            elementFormDefault="qualified">
 <xsd:import namespace="http://ganzua.sourceforge.net/languages"
             schemaLocation="Languages639.xsd"/>
 <xsd:import namespace="http://ganzua.sourceforge.net/countries"
             schemaLocation="Countries3166.xsd"/>

 <xsd:element name="alphabetRules">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:choice>
     <xsd:element name="includeExclusively" type="CharSeq" minOccurs="0"/>
     <xsd:group ref="IncludeIgnore" minOccurs="0"/>
    </xsd:choice>
    <xsd:element name="replace" minOccurs="0">
     <xsd:complexType>
      <xsd:sequence>
       <xsd:element name="occurrences" maxOccurs="unbounded">
        <xsd:complexType>
         <xsd:complexContent>
          <xsd:restriction base="xsd:anyType">
           <xsd:attribute name="ofChar" type="xsd:string" use="required"/>
           <xsd:attribute name="byChar" type="xsd:string" use="required"/>
          </xsd:restriction>
         </xsd:complexContent>
        </xsd:complexType>
       </xsd:element>
      </xsd:sequence>
     </xsd:complexType>
    </xsd:element>
   </xsd:sequence>
   <xsd:attribute name="language" type="lang:language639" use="required"/>
   <xsd:attribute name="country" type="cntry:countries3166" />
   <xsd:attribute name="source" type="xsd:string" use="required"/>
   <xsd:attribute name="sourceEncoding" type="xsd:string" use="required"/>
  </xsd:complexType>
 </xsd:element>

 <xsd:group name="IncludeIgnore">
  <xsd:sequence>
   <xsd:element name="include" type="CharSeq" minOccurs="0"/>
   <xsd:element name="ignore" type="CharSeq" minOccurs="0"/>
  </xsd:sequence>
 </xsd:group>

 <xsd:complexType name="CharSeq">
  <xsd:sequence>
   <xsd:element name="character" maxOccurs="unbounded">
    <xsd:complexType>
     <xsd:complexContent>
      <xsd:restriction base="xsd:anyType">
       <xsd:attribute name="char" type="xsd:string" use="required"/>
      </xsd:restriction>
     </xsd:complexContent>
    </xsd:complexType>
   </xsd:element>
  </xsd:sequence>
 </xsd:complexType>

</xsd:schema>

=== IanGarciaUnam/Criptography/Tarea1/ganzua-1.01-src/ganzua-1.01/examples/alphabetRules/es/ES_27_Min.xml
<?xml version="1.0" encoding="UTF-8"?>
<alphabetRules xmlns="http://ganzua.sourceforge.net/rules"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://ganzua.sourceforge.net/rules
                                   ../schemata/AlphabetRules.xsd"
               language="es" country="ES"
               source="/home/user/examples/es/2donq10.txt"
               sourceEncoding="ISO-8859-15">
 <includeExclusively>
  <character char="a" />
  <character char="b" />
  <character char="c" />
  <character char="d" />
  <character char="e" />
  <character char="f" />
  <character char="g" />
  <character char="h" />
  <character char="i" />
  <character char="j" />
  <character char="k" />
  <character char="l" />
  <character char="m" />
  <character char="n" />
  <character char="ñ" />
  <character char="o" />
  <character char="p" />
  <character char="q" />
  <character char="r" />
  <character char="s" />
  <character char="t" />
  <character char="u" />
  <character char="v" />
  <character char="w" />
  <character char="x" />
  <character char="y" />
  <character char="z" />
 </includeExclusively>
 <replace>
  <occurrences ofChar="á" byChar="a" />
  <occurrences ofChar="à" byChar="a" />
  <occurrences ofChar="é" byChar="e" />
  <occurrences ofChar="í" byChar="i" />
  <occurrences ofChar="ï" byChar="i" />
  <occurrences ofChar="ó" byChar="o" />
  <occurrences ofChar="ú" byChar="u" />
  <occurrences ofChar="ù" byChar="u" />
  <occurrences ofChar="ü" byChar="u" />
  <occurrences ofChar="A" byChar="a" />
  <occurrences ofChar="Á" byChar="a" />
  <occurrences ofChar="B" byChar="b" />
  <occurrences ofChar="C" byChar="c" />
  <occurrences ofChar="D" byChar="d" />
  <occurrences ofChar="E" byChar="e" />
  <occurrences ofChar="É" byChar="e" />
  <occurrences ofChar="F" byChar="f" />
  <occurrences ofChar="G" byChar="g" />
  <occurrences ofChar="H" byChar="h" />
  <occurrences ofChar="I" byChar="i" />
  <occurrences ofChar="Í" byChar="i" />
  <occurrences ofChar="J" byChar="j" />
  <occurrences ofChar="K" byChar="k" />
  <occurrences ofChar="L" byChar="l" />
  <occurrences ofChar="M" byChar="m" />
  <occurrences ofChar="N" byChar="n" />
  <occurrences ofChar="Ñ" byChar="ñ" />
  <occurrences ofChar="O" byChar="o" />
  <occurrences ofChar="Ó" byChar="o" />
  <occurrences ofChar="P" byChar="p" />
  <occurrences ofChar="Q" byChar="q" />
  <occurrences ofChar="R" byChar="r" />
  <occurrences ofChar="S" byChar="s" />
  <occurrences ofChar="T" byChar="t" />
  <occurrences ofChar="U" byChar="u" />
  <occurrences ofChar="Ú" byChar="u" />
  <occurrences ofChar="Ü" byChar="u" />
  <occurrences ofChar="V" byChar="v" />
  <occurrences ofChar="W" byChar="w" />
  <occurrences ofChar="X" byChar="x" />
  <occurrences ofChar="Y" byChar="y" />
  <occurrences ofChar="Z" byChar="z" />
 </replace>
</alphabetRules>

=== IanGarciaUnam/Criptography/Tarea1/ganzua101/ganzua/examples/alphabetRules/en/GB_upperIgnr.xml
<?xml version="1.0" encoding="UTF-8"?>
<alphabetRules xmlns="http://ganzua.sourceforge.net/rules"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://ganzua.sourceforge.net/rules
                                   ../schemata/AlphabetRules.xsd"
               language="en" country="GB"
               source="/home/user/examples/en/cprfd10.txt" 
               sourceEncoding="US-ASCII">
 <include>
  <character char="A" />
  <character char="B" />
  <character char="C" />
  <character char="D" />
  <character char="E" />
  <character char="F" />
  <character char="G" />
  <character char="H" />
  <character char="I" />
  <character char="J" />
  <character char="K" />
  <character char="L" />
  <character char="M" />
  <character char="N" />
  <character char="O" />
  <character char="P" />
  <character char="Q" />
  <character char="R" />
  <character char="S" />
  <character char="T" />
  <character char="U" />
  <character char="V" />
  <character char="W" />
  <character char="X" />
  <character char="Y" />
  <character char="Z" />
 </include>
 <ignore>
  <character char=" " />
  <character char="&#9;" />  <!-- horizontal tab Unicode character reference-->
  <character char="&#10;" /> <!-- line feed -->
  <character char="&#13;" /> <!-- carriage return -->
  <character char="&#13;&#10;" /> <!-- new line -->
  <character char="-" />
  <character char="," />
  <character char=";" />
  <character char=":" />
  <character char="!" />
  <character char="?" />
  <character char="/" />
  <character char="." />
  <character char="&apos;" />
  <character char="&quot;" />
  <character char="(" />
  <character char=")" />
  <character char="&amp;" />
  <character char="0" />
  <character char="1" />
  <character char="2" />
  <character char="3" />
  <character char="4" />
  <character char="5" />
  <character char="6" />
  <character char="7" />
  <character char="8" />
  <character char="9" />
 </ignore>
 <replace>
  <occurrences ofChar="a" byChar="A" />
  <occurrences ofChar="b" byChar="B" />
  <occurrences ofChar="c" byChar="C" />
  <occurrences ofChar="d" byChar="D" />
  <occurrences ofChar="e" byChar="E" />
  <occurrences ofChar="f" byChar="F" />
  <occurrences ofChar="g" byChar="G" />
  <occurrences ofChar="h" byChar="H" />
  <occurrences ofChar="i" byChar="I" />
  <occurrences ofChar="j" byChar="J" />
  <occurrences ofChar="k" byChar="K" />
  <occurrences ofChar="l" byChar="L" />
  <occurrences ofChar="m" byChar="M" />
  <occurrences ofChar="n" byChar="N" />
  <occurrences ofChar="o" byChar="O" />
  <occurrences ofChar="p" byChar="P" />
  <occurrences ofChar="q" byChar="Q" />
  <occurrences ofChar="r" byChar="R" />
  <occurrences ofChar="s" byChar="S" />
  <occurrences ofChar="t" byChar="T" />
  <occurrences ofChar="u" byChar="U" />
  <occurrences ofChar="v" byChar="V" />
  <occurrences ofChar="w" byChar="W" />
  <occurrences ofChar="x" byChar="X" />
  <occurrences ofChar="y" byChar="Y" />
  <occurrences ofChar="z" byChar="Z" />
 </replace>
</alphabetRules>

=== IanGarciaUnam/Criptography/Tarea1/ganzua-1.01-src/ganzua-1.01/examples/alphabetRules/es/ES_27_May_Ignr.xml
<?xml version="1.0" encoding="UTF-8"?>
<alphabetRules xmlns="http://ganzua.sourceforge.net/rules"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://ganzua.sourceforge.net/rules
                                   ../schemata/AlphabetRules.xsd"
               language="es" country="ES"
               source="/home/user/examples/es/2donq10.txt"
               sourceEncoding="ISO-8859-15">
 <include>
  <character char="A" />
  <character char="B" />
  <character char="C" />
  <character char="D" />
  <character char="E" />
  <character char="F" />
  <character char="G" />
  <character char="H" />
  <character char="I" />
  <character char="J" />
  <character char="K" />
  <character char="L" />
  <character char="M" />
  <character char="N" />
  <character char="Ñ" />
  <character char="O" />
  <character char="P" />
  <character char="Q" />
  <character char="R" />
  <character char="S" />
  <character char="T" />
  <character char="U" />
  <character char="V" />
  <character char="W" />
  <character char="X" />
  <character char="Y" />
  <character char="Z" />
 </include>
 <ignore>
  <character char=" " />
  <character char="&#9;" />  <!-- horizontal tab Unicode character reference-->
  <character char="&#10;" /> <!-- line feed -->
  <character char="&#13;" /> <!-- carriage return -->
  <character char="&#13;&#10;" /> <!-- new line -->
  <character char="-" />
  <character char="," />
  <character char=";" />
  <character char=":" />
  <character char="¡" />
  <character char="!" />
  <character char="¿" />
  <character char="?" />
  <character char="." />
  <character char="&apos;" /> <!-- apostrophe entity -->
  <character char="&quot;" /> <!-- quote entity -->
  <character char="«" />
  <character char="»" />
  <character char="(" />
  <character char=")" />
  <character char="[" />
  <character char="]" />
  <character char="0" />
  <character char="1" />
  <character char="2" />
  <character char="3" />
  <character char="4" />
  <character char="5" />
  <character char="6" />
  <character char="7" />
  <character char="8" />
  <character char="9" />
 </ignore>
 <replace>
  <occurrences ofChar="Á" byChar="A" />
  <occurrences ofChar="É" byChar="E" />
  <occurrences ofChar="Í" byChar="I" />
  <occurrences ofChar="Ó" byChar="O" />
  <occurrences ofChar="Ú" byChar="U" />
  <occurrences ofChar="Ü" byChar="U" />
  <occurrences ofChar="a" byChar="A" />
  <occurrences ofChar="á" byChar="A" />
  <occurrences ofChar="à" byChar="A" />
  <occurrences ofChar="b" byChar="B" />
  <occurrences ofChar="c" byChar="C" />
  <occurrences ofChar="d" byChar="D" />
  <occurrences ofChar="e" byChar="E" />
  <occurrences ofChar="é" byChar="E" />
  <occurrences ofChar="f" byChar="F" />
  <occurrences ofChar="g" byChar="G" />
  <occurrences ofChar="h" byChar="H" />
  <occurrences ofChar="i" byChar="I" />
  <occurrences ofChar="í" byChar="I" />
  <occurrences ofChar="ï" byChar="I" />
  <occurrences ofChar="j" byChar="J" />
  <occurrences ofChar="k" byChar="K" />
  <occurrences ofChar="l" byChar="L" />
  <occurrences ofChar="m" byChar="M" />
  <occurrences ofChar="n" byChar="N" />
  <occurrences ofChar="ñ" byChar="Ñ" />
  <occurrences ofChar="o" byChar="O" />
  <occurrences ofChar="ó" byChar="O" />
  <occurrences ofChar="p" byChar="P" />
  <occurrences ofChar="q" byChar="Q" />
  <occurrences ofChar="r" byChar="R" />
  <occurrences ofChar="s" byChar="S" />
  <occurrences ofChar="t" byChar="T" />
  <occurrences ofChar="u" byChar="U" />
  <occurrences ofChar="ú" byChar="U" />
  <occurrences ofChar="ù" byChar="U" />
  <occurrences ofChar="ü" byChar="U" />
  <occurrences ofChar="v" byChar="V" />
  <occurrences ofChar="w" byChar="W" />
  <occurrences ofChar="x" byChar="X" />
  <occurrences ofChar="y" byChar="Y" />
  <occurrences ofChar="z" byChar="Z" />
 </replace>
</alphabetRules>

=== IanGarciaUnam/Criptography/Tarea1/ganzua101/ganzua/examples/alphabetRules/en/GB_lowerIgnr.xml
<?xml version="1.0" encoding="UTF-8"?>
<alphabetRules xmlns="http://ganzua.sourceforge.net/rules"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://ganzua.sourceforge.net/rules
                                   ../schemata/AlphabetRules.xsd"
               language="en" country="GB"
               source="/home/user/examples/en/cprfd10.txt" 
               sourceEncoding="US-ASCII">
 <include>
  <character char="a" />
  <character char="b" />
  <character char="c" />
  <character char="d" />
  <character char="e" />
  <character char="f" />
  <character char="g" />
  <character char="h" />
  <character char="i" />
  <character char="j" />
  <character char="k" />
  <character char="l" />
  <character char="m" />
  <character char="n" />
  <character char="o" />
  <character char="p" />
  <character char="q" />
  <character char="r" />
  <character char="s" />
  <character char="t" />
  <character char="u" />
  <character char="v" />
  <character char="w" />
  <character char="x" />
  <character char="y" />
  <character char="z" />
 </include>
 <ignore>
  <character char=" " />
  <character char="&#9;" />  <!-- horizontal tab Unicode character reference-->
  <character char="&#10;" /> <!-- line feed -->
  <character char="&#13;" /> <!-- carriage return -->
  <character char="&#13;&#10;" /> <!-- new line -->
  <character char="-" />
  <character char="," />
  <character char=";" />
  <character char=":" />
  <character char="!" />
  <character char="?" />
  <character char="/" />
  <character char="." />
  <character char="&apos;" />
  <character char="&quot;" />
  <character char="(" />
  <character char=")" />
  <character char="&amp;" />
  <character char="0" />
  <character char="1" />
  <character char="2" />
  <character char="3" />
  <character char="4" />
  <character char="5" />
  <character char="6" />
  <character char="7" />
  <character char="8" />
  <character char="9" />
 </ignore>
 <replace>
  <occurrences ofChar="A" byChar="a" />
  <occurrences ofChar="B" byChar="b" />
  <occurrences ofChar="C" byChar="c" />
  <occurrences ofChar="D" byChar="d" />
  <occurrences ofChar="E" byChar="e" />
  <occurrences ofChar="F" byChar="f" />
  <occurrences ofChar="G" byChar="g" />
  <occurrences ofChar="H" byChar="h" />
  <occurrences ofChar="I" byChar="i" />
  <occurrences ofChar="J" byChar="j" />
  <occurrences ofChar="K" byChar="k" />
  <occurrences ofChar="L" byChar="l" />
  <occurrences ofChar="M" byChar="m" />
  <occurrences ofChar="N" byChar="n" />
  <occurrences ofChar="O" byChar="o" />
  <occurrences ofChar="P" byChar="p" />
  <occurrences ofChar="Q" byChar="q" />
  <occurrences ofChar="R" byChar="r" />
  <occurrences ofChar="S" byChar="s" />
  <occurrences ofChar="T" byChar="t" />
  <occurrences ofChar="U" byChar="u" />
  <occurrences ofChar="V" byChar="v" />
  <occurrences ofChar="W" byChar="w" />
  <occurrences ofChar="X" byChar="x" />
  <occurrences ofChar="Y" byChar="y" />
  <occurrences ofChar="Z" byChar="z" />
 </replace>
</alphabetRules>
